[package]
name = "simulation-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lib-simulation = { path = "../../libs/simulation" }
wasm-bindgen = "0.2.100"
rand = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
