[package]
name = "simulation-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }
